version: "3.5"
services:
  maiia:
    restart: "no"
    build:
      context: .
      args:
        base_image: tensorflow/tensorflow:2.8.0-gpu-jupyter
    image: maiia
    # use the nvidia runtime to access gpu (only if nvidia-docker installed!):
    runtime: "nvidia"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # allows access to some of outside filesystem including host devices
    # (webcam, gpu etc)
    privileged: true
    ports:
      - "8888:8888"
    # network mode
    #network_mode: "bridge"
    stdin_open: true
    tty: true
    #entrypoint: /bin/bash
    # shared volumes
    volumes:
      - type: bind
        source: ./notebooks
        target: /tf/notebooks
      - type: bind
        source: ./data
        target: /app/data
